sudo: required
services:
  - docker

before_install:
  - docker build -t nikbhatia13/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true -d -p 80:80 nikbhatia13/docker-react

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-854359595163"
  bucket_path: "docker-react"
  on:
    branch: main
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
